### ISSUE TITLE
Currently rendering this qmd is broken due to upstream change

### ISSUE THREAD

**Issue by psobolewskiPhD** [psobolewskiPhD/intro-napari-slides#3]
See:
https://github.com/quarto-dev/quarto-cli/issues/9821

This is due to using a callout with just a title:
```
::: {.callout-tip}
## Title only
:::
```
e.g. the title slide COI notice.

**Comment by cscheid** [comment]
(Quarto dev here) This is a Quarto bug, and a bad one at that! Thank you for reporting. We'll fix right away.

**Comment by psobolewskiPhD** [comment]
This has been fixed upstream. I also reverted my first guess at fixing it (https://github.com/TheJacksonLaboratory/intro-napari-slides/pull/2)
